"""Compare desired Reform BOM edges with the current Odoo BOM map.

Inputs are generated by reform_map.py and odoo_map.py.  SKU matching is
case-insensitive. Purely numeric SKUs are also compared without leading zeros,
but original SKU spelling is retained in the output.
"""

from __future__ import annotations

import argparse
import re
from collections import Counter, defaultdict
from pathlib import Path
from typing import Iterable

from openpyxl import Workbook, load_workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter


# =============================================================================
# PALYGINIMO PLANAS
# 1. Perskaitome Reform ir Odoo MAP failų tiesioginius BOM ryšius.
# 2. Suvienodiname SKU tik palyginimui, bet rezultate paliekame originalų tekstą.
# 3. Kiekvienam Reform komponentui ieškome atitikmens tiesiogiai arba per -PP.
# 4. Atskirai pažymime pakuotės komponentus, kad jų nesiūlytume šalinti.
# 5. Sukuriame valdymo lapus: nauji BOM, pakeitimai ir peržiūros sąrašai.
# 6. Nieko neimportuojame į Odoo – ši programa tik paruošia Excel peržiūrai.
# =============================================================================

EPSILON = 1e-9


def canon(value: object) -> str:
    text = str(value or "").strip().upper()
    # Importuojant per Excel, Odoo gali pašalinti skaitinio Internal Reference
    # pradinius nulius. Todėl 0217129846 ir 217129846 laikome tuo pačiu SKU.
    if text.isdigit():
        return text.lstrip("0") or "0"
    return text


def same_qty(left: float, right: float) -> bool:
    return abs(left - right) <= EPSILON


def as_number(value: float) -> int | float:
    rounded = round(value)
    return rounded if same_qty(value, rounded) else round(value, 8)


# 1 ŽINGSNIS: perskaitome vieno MAP failo Parent–Component–Quantity ryšius.
# Pasikartojančios vienodos eilutės sumuojamos, nes BOM'e tas pats komponentas
# gali būti įrašytas keliose eilutėse.
def load_edges(path: Path, sheet_name: str):
    wb = load_workbook(path, read_only=True, data_only=True)
    if sheet_name not in wb.sheetnames:
        raise ValueError(f"Faile {path.name} nėra lapo {sheet_name!r}.")
    ws = wb[sheet_name]
    rows = ws.iter_rows(values_only=True)
    headers = next(rows, None)
    if not headers:
        raise ValueError(f"Lapas {sheet_name!r} yra tuščias.")
    index = {str(value).strip(): i for i, value in enumerate(headers) if value is not None}
    required = {"Parent SKU", "Component SKU", "Quantity"}
    missing = required - set(index)
    if missing:
        raise ValueError(f"Lape {sheet_name!r} trūksta stulpelių: {', '.join(sorted(missing))}")

    aggregated = defaultdict(float)
    originals: dict[tuple[str, str], tuple[str, str]] = {}
    raw_count = 0
    diagnostics = []
    for excel_row, row in enumerate(rows, start=2):
        parent_raw = row[index["Parent SKU"]]
        component_raw = row[index["Component SKU"]]
        quantity_raw = row[index["Quantity"]]
        parent, component = canon(parent_raw), canon(component_raw)
        if not parent or not component:
            diagnostics.append((path.name, sheet_name, excel_row, "Praleistas tuščias Parent arba Component SKU"))
            continue
        try:
            quantity = float(quantity_raw)
        except (TypeError, ValueError):
            diagnostics.append((path.name, sheet_name, excel_row, f"Netinkamas kiekis: {quantity_raw!r}"))
            continue
        raw_count += 1
        key = (parent, component)
        aggregated[key] += quantity
        originals.setdefault(key, (str(parent_raw).strip(), str(component_raw).strip()))
    wb.close()

    graph = defaultdict(dict)
    for (parent, component), quantity in aggregated.items():
        graph[parent][component] = quantity
    return dict(aggregated), dict(graph), originals, raw_count, diagnostics


def load_selected_odoo_parents(path: Path) -> set[str]:
    wb = load_workbook(path, read_only=True, data_only=True)
    result: set[str] = set()
    if "BOM SELECTION" in wb.sheetnames:
        ws = wb["BOM SELECTION"]
        rows = ws.iter_rows(values_only=True)
        headers = next(rows, ())
        index = {str(value).strip(): i for i, value in enumerate(headers) if value is not None}
        if "Parent SKU" in index and "Status" in index:
            for row in rows:
                if canon(row[index["Status"]]) == "SELECTED":
                    result.add(canon(row[index["Parent SKU"]]))
    wb.close()
    return result


def load_new_products(path: Path) -> set[str]:
    wb = load_workbook(path, read_only=True, data_only=True)
    if "PRODUCT DETECTION" not in wb.sheetnames:
        raise ValueError(f"Faile {path.name} nėra lapo 'PRODUCT DETECTION'.")
    ws = wb["PRODUCT DETECTION"]
    rows = ws.iter_rows(values_only=True)
    headers = next(rows, ())
    index = {str(value).strip(): i for i, value in enumerate(headers) if value is not None}
    required = {"Reform SKU", "Exists in Odoo"}
    if not required <= set(index):
        raise ValueError(f"Faile {path.name} trūksta Product Detection stulpelių.")
    result = set()
    for row in rows:
        exists = canon(row[index["Exists in Odoo"]])
        if exists in {"NO", "NE", "FALSE", "0"}:
            result.add(canon(row[index["Reform SKU"]]))
    wb.close()
    return result


def load_reform_product_metadata(path: Path) -> dict[str, dict]:
    wb = load_workbook(path, read_only=True, data_only=True)
    for ws in wb.worksheets:
        header_row = None
        headers = None
        for row_no, row in enumerate(ws.iter_rows(min_row=1, max_row=min(ws.max_row, 30), values_only=True), start=1):
            values = [str(v).strip() if v is not None else "" for v in row]
            if "BOM SKU Code" in values:
                header_row, headers = row_no, values
                break
        if not header_row:
            continue
        index = {value: i for i, value in enumerate(headers) if value}
        result = {}
        for row in ws.iter_rows(min_row=header_row + 1, values_only=True):
            sku_raw = row[index["BOM SKU Code"]]
            sku = canon(sku_raw)
            if not sku:
                continue
            result[sku] = {
                "SKU": str(sku_raw).strip(),
                "Category": str(row[index.get("Product Catagory", -1)] or "UNCLASSIFIED").strip(),
                "Name 1": str(row[index.get("SKU name 1", -1)] or "").strip(),
                "Name 2": str(row[index.get("SKU name 2", -1)] or "").strip(),
            }
        wb.close()
        return result
    wb.close()
    raise ValueError(f"Faile {path.name} nerastas 'BOM SKU Code' antraštės stulpelis.")


# 3A ŽINGSNIS: jei tiesioginio ryšio nėra, ieškome dviejų lygių kelio:
# Parent -> tarpinis produktas (-PP) -> Component.
# Efektyvus kiekis = išorinis kiekis * vidinis kiekis.
def choose_path(parent: str, component: str, reform_qty: float, odoo_graph):
    candidates = []
    for middle, outer_qty in odoo_graph.get(parent, {}).items():
        inner_qty = odoo_graph.get(middle, {}).get(component)
        if inner_qty is not None:
            effective = outer_qty * inner_qty
            candidates.append((middle, outer_qty, inner_qty, effective))
    if not candidates:
        return None
    # Prefer an exact effective quantity, then a -PP wrapper, then stable SKU order.
    candidates.sort(key=lambda x: (not same_qty(x[3], reform_qty), not x[0].endswith("-PP"), x[0]))
    return candidates[0]


# 3B ŽINGSNIS: atliekame pagrindinį BOM palyginimą.
# Galimi sprendimai:
# - MATCH: komponentas ir kiekis sutampa;
# - CHANGE QUANTITY: komponentas yra, bet kiekis skiriasi;
# - MATCH THROUGH -PP: komponentas rastas per tarpinį -PP;
# - ADD COMPONENT: Reform komponento Odoo BOM'e nerasta;
# - CREATE BOM: produktas yra, tačiau pasirinkto Odoo BOM nėra.
def compare(reform_edges, odoo_edges, reform_graph, odoo_graph, selected_odoo_parents,
            reform_originals, odoo_originals):
    rows = []
    consumed_odoo_edges: set[tuple[str, str]] = set()
    wrapper_usage: dict[tuple[str, str], set[str]] = defaultdict(set)

    for (parent, component), reform_qty in sorted(reform_edges.items()):
        r_parent, r_component = reform_originals[(parent, component)]
        odoo_qty = odoo_edges.get((parent, component))
        middle = ""
        route = "DIRECT"
        product_exists = parent in selected_odoo_parents or parent in odoo_graph

        if not product_exists:
            status = "CREATE BOM"
            effective_qty = None
            route = "NO ODOO BOM"
        elif odoo_qty is not None:
            consumed_odoo_edges.add((parent, component))
            effective_qty = odoo_qty
            status = "MATCH" if same_qty(reform_qty, odoo_qty) else "CHANGE QUANTITY"
        else:
            path = choose_path(parent, component, reform_qty, odoo_graph)
            if path:
                middle, outer_qty, inner_qty, effective_qty = path
                consumed_odoo_edges.update({(parent, middle), (middle, component)})
                wrapper_usage[(parent, middle)].add(component)
                route = "THROUGH -PP" if middle.endswith("-PP") else "THROUGH COMPONENT"
                status = f"MATCH {route}" if same_qty(reform_qty, effective_qty) else f"CHANGE QUANTITY {route}"
            else:
                effective_qty = None
                status = "ADD COMPONENT"
                route = "NOT FOUND IN ODOO BOM"

        o_parent, o_component = odoo_originals.get((parent, component), ("", ""))
        rows.append({
            "Status": status,
            "Parent SKU": r_parent,
            "Reform Component SKU": r_component,
            "Reform Quantity": as_number(reform_qty),
            "Odoo Component SKU": o_component,
            "Odoo Quantity / Effective Quantity": "" if effective_qty is None else as_number(effective_qty),
            "Intermediate SKU": odoo_originals.get((parent, middle), ("", middle))[1] if middle else "",
            "Route": route,
            "Parent Has Odoo BOM": "YES" if product_exists else "NO",
        })

    # 4 ŽINGSNIS: komponentus, esančius tik -PP pakuotėje, atskiriame nuo
    # tikrų BOM skirtumų. Jie neturi tapti REMOVE COMPONENT pasiūlymais.
    packaging_rows = []
    for (parent, wrapper), matched_components in sorted(wrapper_usage.items()):
        outer_qty = odoo_graph[parent][wrapper]
        for child, inner_qty in sorted(odoo_graph.get(wrapper, {}).items()):
            if child in matched_components:
                continue
            effective = outer_qty * inner_qty
            p_display = reform_originals.get((parent, next(iter(matched_components))), (parent, ""))[0]
            wrapper_display = odoo_originals.get((parent, wrapper), ("", wrapper))[1]
            child_display = odoo_originals.get((wrapper, child), ("", child))[1]
            packaging_rows.append({
                "Status": "PACKAGING ONLY",
                "Parent SKU": p_display,
                "Wrapper SKU": wrapper_display,
                "Packaging Component SKU": child_display,
                "Placement in Odoo": "INSIDE WRAPPER",
                "Outer Quantity": as_number(outer_qty),
                "Inner Quantity": as_number(inner_qty),
                "Effective Quantity": as_number(effective),
            })
            consumed_odoo_edges.add((wrapper, child))

    # Only extras directly under a Reform parent are candidates for removal.
    # Wrapper edges already used by an indirect match are consumed above.
    removal_rows = []
    known_packaging_components = {
        canon(row["Packaging Component SKU"]) for row in packaging_rows
    }
    for (parent, component), quantity in sorted(odoo_edges.items()):
        if parent not in reform_graph or (parent, component) in consumed_odoo_edges:
            continue
        parent_display, component_display = odoo_originals[(parent, component)]
        if component in known_packaging_components:
            packaging_rows.append({
                "Status": "PACKAGING ONLY",
                "Parent SKU": parent_display,
                "Wrapper SKU": "",
                "Packaging Component SKU": component_display,
                "Placement in Odoo": "DIRECT UNDER PARENT",
                "Outer Quantity": "",
                "Inner Quantity": as_number(quantity),
                "Effective Quantity": as_number(quantity),
            })
            continue
        removal_rows.append({
            "Status": "REMOVE COMPONENT",
            "Parent SKU": parent_display,
            "Odoo Component SKU": component_display,
            "Odoo Quantity": as_number(quantity),
        })

    return rows, packaging_rows, removal_rows


def add_table_sheet(wb: Workbook, title: str, headers: list[str], rows: Iterable[dict]):
    ws = wb.create_sheet(title)
    ws.append(headers)
    for record in rows:
        ws.append([record.get(header, "") for header in headers])
    header_fill = PatternFill("solid", fgColor="1F4E78")
    for cell in ws[1]:
        cell.font = Font(color="FFFFFF", bold=True)
        cell.fill = header_fill
        cell.alignment = Alignment(horizontal="center")
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = ws.dimensions
    for col_idx, header in enumerate(headers, start=1):
        values = [str(ws.cell(row=r, column=col_idx).value or "") for r in range(1, min(ws.max_row, 500) + 1)]
        width = min(max(max(map(len, values), default=len(header)) + 2, 12), 48)
        ws.column_dimensions[get_column_letter(col_idx)].width = width
    return ws


# 5A ŽINGSNIS: iš techninio palyginimo sudarome žmogui skirtus valdymo sąrašus:
# nauji produktai, nauji BOM, naujos BOM eilutės ir esamų BOM pakeitimai.
def build_management_tables(comparison, removals, new_product_skus, product_metadata):
    reform_parent_display = {}
    for row in comparison:
        reform_parent_display.setdefault(canon(row["Parent SKU"]), row["Parent SKU"])

    new_products = []
    for sku in sorted(new_product_skus):
        meta = product_metadata.get(sku, {})
        new_products.append({
            "SKU": meta.get("SKU", reform_parent_display.get(sku, sku)),
            "Category": meta.get("Category", "UNCLASSIFIED"),
            "Product Name 1": meta.get("Name 1", ""),
            "Product Name 2": meta.get("Name 2", ""),
            "Required Action": "CREATE PRODUCT",
        })
    category_counts = Counter(row["Category"] or "UNCLASSIFIED" for row in new_products)
    category_rows = [{"Category": category, "New Product Count": count}
                     for category, count in sorted(category_counts.items())]

    create_bom_rows = [row for row in comparison if row["Status"] == "CREATE BOM"]
    new_bom_parents = sorted({canon(row["Parent SKU"]) for row in create_bom_rows})
    new_boms = []
    for sku in new_bom_parents:
        meta = product_metadata.get(sku, {})
        line_count = sum(canon(row["Parent SKU"]) == sku for row in create_bom_rows)
        new_boms.append({
            "Parent SKU": meta.get("SKU", reform_parent_display.get(sku, sku)),
            "Category": meta.get("Category", "UNCLASSIFIED"),
            "Product Name 1": meta.get("Name 1", ""),
            "Product Name 2": meta.get("Name 2", ""),
            "BOM Line Count": line_count,
            "Product Status": "NEW PRODUCT" if sku in new_product_skus else "PRODUCT EXISTS IN ODOO",
            "Required Action": "CREATE PRODUCT + BOM" if sku in new_product_skus else "CREATE BOM",
        })
    new_bom_lines = [{
        "Parent SKU": row["Parent SKU"],
        "Component SKU": row["Reform Component SKU"],
        "Quantity": row["Reform Quantity"],
        "Required Action": "ADD BOM LINE",
    } for row in create_bom_rows]

    change_rows = []
    for row in comparison:
        if row["Status"] == "ADD COMPONENT":
            action = "ADD COMPONENT"
        elif row["Status"].startswith("CHANGE QUANTITY"):
            action = "CHANGE QUANTITY"
        else:
            continue
        change_rows.append({
            "Parent SKU": row["Parent SKU"], "Required Action": action,
            "Component SKU": row["Reform Component SKU"],
            "Current Odoo Quantity": row["Odoo Quantity / Effective Quantity"],
            "Required Reform Quantity": row["Reform Quantity"],
            "Intermediate SKU": row["Intermediate SKU"], "Route": row["Route"],
        })
    for row in removals:
        change_rows.append({
            "Parent SKU": row["Parent SKU"], "Required Action": "REVIEW / REMOVE COMPONENT",
            "Component SKU": row["Odoo Component SKU"],
            "Current Odoo Quantity": row["Odoo Quantity"],
            "Required Reform Quantity": "", "Intermediate SKU": "", "Route": "DIRECT",
        })

    grouped = defaultdict(Counter)
    display = {}
    for row in change_rows:
        parent = canon(row["Parent SKU"])
        display[parent] = row["Parent SKU"]
        grouped[parent][row["Required Action"]] += 1
    change_summary = []
    for parent in sorted(grouped):
        counts = grouped[parent]
        meta = product_metadata.get(parent, {})
        change_summary.append({
            "Parent SKU": display[parent], "Category": meta.get("Category", "UNCLASSIFIED"),
            "Add Components": counts["ADD COMPONENT"],
            "Change Quantities": counts["CHANGE QUANTITY"],
            "Review / Remove Components": counts["REVIEW / REMOVE COMPONENT"],
            "Total Changes": sum(counts.values()),
        })
    return new_products, category_rows, new_boms, new_bom_lines, change_summary, change_rows


# 5B ŽINGSNIS: visus rezultatus įrašome į vieną MAP_Comparison.xlsx failą.
# Ši funkcija tik rašo ataskaitą – Odoo duomenų nekeičia.
def write_output(path: Path, comparison, packaging, removals, diagnostics, metadata,
                 new_product_skus, product_metadata):
    (new_products, category_rows, new_boms, new_bom_lines,
     change_summary, change_rows) = build_management_tables(
        comparison, removals, new_product_skus, product_metadata
    )
    wb = Workbook()
    summary = wb.active
    summary.title = "SUMMARY"
    counts = Counter(row["Status"] for row in comparison if row["Status"] != "CREATE BOM")
    counts["PACKAGING ONLY"] = len(packaging)
    counts["REMOVE COMPONENT"] = len(removals)
    counts["NEW PRODUCTS"] = len(new_products)
    counts["NEW BOMS"] = len(new_boms)
    counts["NEW BOM LINES"] = len(new_bom_lines)
    counts["EXISTING BOMS WITH CHANGES"] = len(change_summary)
    summary.append(["Status", "Count"])
    for status, count in sorted(counts.items()):
        summary.append([status, count])
    summary.append([])
    summary.append(["Parent metric", "Count"])
    summary.append(["Reform parents", metadata.pop("Reform parents")])
    summary.append(["Parents without Odoo BOM", metadata.pop("Parents without Odoo BOM")])
    summary.append([])
    summary.append(["Parameter", "Value"])
    for key, value in metadata.items():
        summary.append([key, value])
    for row_number in (1, 1 + len(counts) + 2, summary.max_row - len(metadata)):
        for cell in summary[row_number]:
            cell.font = Font(color="FFFFFF", bold=True)
            cell.fill = PatternFill("solid", fgColor="1F4E78")
    summary.column_dimensions["A"].width = 42
    summary.column_dimensions["B"].width = 18
    summary.freeze_panes = "A2"

    add_table_sheet(wb, "NEW PRODUCTS", ["SKU", "Category", "Product Name 1",
                    "Product Name 2", "Required Action"], new_products)
    add_table_sheet(wb, "NEW PRODUCTS BY CATEGORY", ["Category", "New Product Count"], category_rows)
    add_table_sheet(wb, "NEW BOMS", ["Parent SKU", "Category", "Product Name 1", "Product Name 2",
                    "BOM Line Count", "Product Status", "Required Action"], new_boms)
    add_table_sheet(wb, "NEW BOM LINES", ["Parent SKU", "Component SKU", "Quantity", "Required Action"], new_bom_lines)
    add_table_sheet(wb, "BOM CHANGE SUMMARY", ["Parent SKU", "Category", "Add Components",
                    "Change Quantities", "Review / Remove Components", "Total Changes"], change_summary)
    add_table_sheet(wb, "BOM CHANGES", ["Parent SKU", "Required Action", "Component SKU",
                    "Current Odoo Quantity", "Required Reform Quantity", "Intermediate SKU", "Route"], change_rows)

    comparison_headers = ["Status", "Parent SKU", "Reform Component SKU", "Reform Quantity",
                          "Odoo Component SKU", "Odoo Quantity / Effective Quantity",
                          "Intermediate SKU", "Route", "Parent Has Odoo BOM"]
    add_table_sheet(wb, "COMPARISON", comparison_headers, comparison)
    add_table_sheet(wb, "CREATE BOM", comparison_headers,
                    (row for row in comparison if row["Status"] == "CREATE BOM"))
    add_table_sheet(wb, "PACKAGING", ["Status", "Parent SKU", "Wrapper SKU",
                    "Packaging Component SKU", "Placement in Odoo", "Outer Quantity",
                    "Inner Quantity", "Effective Quantity"], packaging)
    add_table_sheet(wb, "REMOVE COMPONENT", ["Status", "Parent SKU", "Odoo Component SKU", "Odoo Quantity"], removals)
    diag_headers = ["Source File", "Sheet", "Row", "Message"]
    add_table_sheet(wb, "DIAGNOSTICS", diag_headers,
                    ({h: v for h, v in zip(diag_headers, row)} for row in diagnostics))
    path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(path)


def find_input(directory: Path, name: str) -> Path:
    candidates = [directory / name, directory / "output" / name, directory / "upload" / name]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    raise FileNotFoundError(f"Nerastas {name}. Nurodykite failą su komandiniu parametru.")


def find_reform_bom_input(directory: Path) -> Path:
    patterns = ["Reform_BOM_Input*.xlsx", "BOM_for Furnibox*.xlsx"]
    candidates = []
    for folder in (directory / "data", directory / "upload", directory):
        for pattern in patterns:
            candidates.extend(folder.glob(pattern))
    candidates = [p for p in candidates if not p.name.startswith("~$")]
    if not candidates:
        raise FileNotFoundError("Nerastas Reform BOM Input failas. Naudokite --bom-input.")
    return max(candidates, key=lambda p: p.stat().st_mtime)


def main():
    parser = argparse.ArgumentParser(description="Palygina Reform ir Odoo BOM MAP tiesioginius ryšius.")
    parser.add_argument("--reform", type=Path, help="Reform_MAP.xlsx kelias")
    parser.add_argument("--odoo", type=Path, help="Odoo_MAP.xlsx kelias")
    parser.add_argument("--output", type=Path, help="Rezultato .xlsx kelias")
    parser.add_argument("--products", type=Path, help="Product_Detection_All.xlsx kelias")
    parser.add_argument("--bom-input", type=Path, help="Reform BOM Input .xlsx kelias")
    args = parser.parse_args()

    # 1. Randame šaltinius. Product_Detection_All.xlsx yra galutinis visų
    # produktų patikrinimas, todėl senas Product_Detection.xlsx nenaudojamas.
    base = Path(__file__).resolve().parent
    reform_path = args.reform or find_input(base, "Reform_MAP.xlsx")
    odoo_path = args.odoo or find_input(base, "Odoo_MAP.xlsx")
    output_path = args.output or base / "output" / "MAP_Comparison.xlsx"
    products_path = args.products or find_input(base, "Product_Detection_All.xlsx")
    bom_input_path = args.bom_input or find_reform_bom_input(base)

    # 2. Nuskaitome Reform norimą struktūrą ir dabartinę Odoo struktūrą.
    reform_edges, reform_graph, reform_originals, reform_raw, reform_diag = load_edges(reform_path, "REFORM EDGES")
    odoo_edges, odoo_graph, odoo_originals, odoo_raw, odoo_diag = load_edges(odoo_path, "ODOO EDGES")
    selected_parents = load_selected_odoo_parents(odoo_path)
    new_product_skus = load_new_products(products_path)
    product_metadata = load_reform_product_metadata(bom_input_path)
    # 3–4. Palyginame ryšius ir atskiriame pakuotę nuo tikrų pakeitimų.
    comparison, packaging, removals = compare(
        reform_edges, odoo_edges, reform_graph, odoo_graph, selected_parents,
        reform_originals, odoo_originals,
    )
    diagnostics = reform_diag + odoo_diag
    # 5–6. Sukuriame Excel peržiūrai. Šiame etape Odoo importas nevyksta.
    write_output(output_path, comparison, packaging, removals, diagnostics, {
        "Reform source": str(reform_path),
        "Odoo source": str(odoo_path),
        "Reform raw edges": reform_raw,
        "Reform normalized edges": len(reform_edges),
        "Odoo raw edges": odoo_raw,
        "Odoo normalized edges": len(odoo_edges),
        "Reform parents": len(reform_graph),
        "Parents without Odoo BOM": len(set(reform_graph) - (selected_parents | set(odoo_graph))),
        "SKU comparison": "TRIM + UPPERCASE + NUMERIC LEADING-ZERO NORMALIZATION",
        "Quantity tolerance": EPSILON,
        "Product detection source": str(products_path),
        "Reform BOM input source": str(bom_input_path),
    }, new_product_skus, product_metadata)

    counts = Counter(row["Status"] for row in comparison if row["Status"] != "CREATE BOM")
    print("\nMAP PALYGINIMAS SUKURTAS")
    print("Failas:", output_path)
    for status, count in sorted(counts.items()):
        print(f"{status}: {count}")
    create_bom_rows = [row for row in comparison if row["Status"] == "CREATE BOM"]
    print("NEW BOMS:", len({canon(row["Parent SKU"]) for row in create_bom_rows}))
    print("NEW BOM LINES:", len(create_bom_rows))
    print("PACKAGING ONLY:", len(packaging))
    print("REMOVE COMPONENT:", len(removals))
    print("Diagnostikos įrašai:", len(diagnostics))


if __name__ == "__main__":
    main()

